import { GoogleGenAI, Modality, Type, ThinkingLevel, GenerateContentResponse } from "@google/genai";
import OpenAI from "openai";

// Initialize the AI client
// Note: process.env.GEMINI_API_KEY is injected by the platform
// We initialize it inside functions to ensure fresh API key usage
const getApiKey = () => {
  const manualKey = typeof window !== 'undefined' ? localStorage.getItem('OMNIGEN_CUSTOM_KEY') : null;
  return manualKey || process.env.GEMINI_API_KEY || "";
};

const getAimlKey = () => {
  const manual = typeof window !== 'undefined' ? localStorage.getItem('OMNIGEN_AIML_KEY') : null;
  return manual || "ab331efe3369c7d6fbf60941b60d5f94"; // Use provided key as default
};

const getJson2videoKey = () => {
  return typeof window !== 'undefined' ? localStorage.getItem('OMNIGEN_JSON2VIDEO_KEY') : null;
};

export const models = {
  text: "gemini-3-flash-preview",
  pro: "gemini-3.1-pro-preview",
  image: "gemini-3.1-flash-image-preview",
  video: "veo-3.1-lite-generate-preview",
  aiml: "claude-opus-4-6",
  seedance: "bytedance/seedance-1-0-lite-t2v",
  sora: "sora-2-t2v"
};

export async function generateText(prompt: string, systemInstruction?: string) {
  const aimlKey = getAimlKey();
  
  if (aimlKey) {
    try {
      const client = new OpenAI({
        apiKey: aimlKey,
        baseURL: "https://ai.aimlapi.com",
        dangerouslyAllowBrowser: true
      });
      
      const response = await client.chat.completions.create({
        model: models.aiml,
        messages: [
          ...(systemInstruction ? [{ role: "system" as const, content: systemInstruction }] : []),
          { role: "user" as const, content: prompt }
        ],
      });
      
      return response.choices[0].message.content || "No response from AIML API";
    } catch (error) {
      console.error("AIML API Error, falling back to Gemini:", error);
    }
  }

  const ai = new GoogleGenAI({ apiKey: getApiKey() });
  const response = await ai.models.generateContent({
    model: models.text,
    contents: prompt,
    config: {
      systemInstruction,
    },
  });
  return response.text;
}

export async function generateImage(prompt: string, referenceImage?: string) {
  const ai = new GoogleGenAI({ apiKey: getApiKey() });
  const parts: any[] = [{ text: prompt }];
  
  if (referenceImage) {
    const base64Data = referenceImage.split(',')[1] || referenceImage;
    const mimeType = referenceImage.match(/^data:(.*);base64,/)?.[1] || 'image/jpeg';
    parts.unshift({ inlineData: { data: base64Data, mimeType } });
  }

  const response = await ai.models.generateContent({
    model: models.image,
    contents: {
      parts,
    },
    config: {
      imageConfig: {
        aspectRatio: "1:1",
        imageSize: "1K"
      }
    }
  });

  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
    }
  }
  throw new Error("No image generated by the AI model.");
}

export async function generateVideo(prompt: string, imageBase64?: string) {
  const json2videoKey = getJson2videoKey();
  const aimlKey = getAimlKey();
  
  if (json2videoKey) {
    try {
      // JSON2Video API call
      const response = await fetch('https://api.json2video.com/v2/jobs', {
        method: 'POST',
        headers: {
          'x-api-key': json2videoKey,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          "scenes": [
            {
              "elements": [
                {
                  "type": "text",
                  "text": prompt,
                  "duration": 5
                }
              ]
            }
          ]
        }),
      });

      const data = await response.json();
      if (!response.ok) throw new Error(data.message || "JSON2Video API Error");

      const jobId = data.project;
      
      // Polling for JSON2Video
      let status = 'pending';
      let videoUrl = '';
      while (status !== 'completed' && status !== 'error') {
        await new Promise(resolve => setTimeout(resolve, 5000));
        const pollRes = await fetch(`https://api.json2video.com/v2/jobs/${jobId}`, {
          headers: { 'x-api-key': json2videoKey }
        });
        const pollData = await pollRes.json();
        status = pollData.status;
        videoUrl = pollData.url;
        if (status === 'error') throw new Error("JSON2Video generation failed");
      }
      return videoUrl;
    } catch (error) {
      console.error("JSON2Video Error, falling back to AIML:", error);
    }
  }

  if (!aimlKey) {
    throw new Error("AIML API Key or JSON2Video Key is required for video generation.");
  }

  try {
    const response = await fetch('https://ai.aimlapi.com/v1/video/generations', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${aimlKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        "model": models.sora,
        "prompt": prompt
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`AIML API Error: ${response.status} - ${errorText}`);
    }

    const data = await response.json();
    
    // Handle direct URL if available
    if (data.url) return data.url;
    if (data.output && data.output.url) return data.output.url;

    const taskId = data.id || data.task_id;
    if (!taskId) {
      throw new Error("No task ID returned from AIML API");
    }

    // Polling logic for v1
    const timeout = 600 * 1000; // 10 minutes
    const startTime = Date.now();

    while (Date.now() - startTime < timeout) {
      const pollRes = await fetch(`https://ai.aimlapi.com/v1/video/generations/${taskId}`, {
        headers: {
          'Authorization': `Bearer ${aimlKey}`,
          'Content-Type': 'application/json',
        }
      });

      if (!pollRes.ok) {
        throw new Error(`Polling failed: ${pollRes.status}`);
      }

      const pollData = await pollRes.json();
      const status = pollData.status;

      if (status === 'completed' || status === 'success') {
        return pollData.url || (pollData.output && pollData.output.url) || pollData.video_url;
      }

      if (['failed', 'error', 'cancelled'].includes(status)) {
        throw new Error(`Video generation failed with status: ${status}`);
      }

      // Still processing
      await new Promise((resolve) => setTimeout(resolve, 10000));
    }

    throw new Error("Video generation timed out");
  } catch (error) {
    console.error("AIML Video Error:", error);
    throw error;
  }
}

export async function analyzeMedia(prompt: string, mediaData: string, mimeType: string) {
  const ai = new GoogleGenAI({ apiKey: getApiKey() });
  const base64Data = mediaData.split(',')[1] || mediaData;
  const response = await ai.models.generateContent({
    model: models.text,
    contents: {
      parts: [
        { inlineData: { data: base64Data, mimeType } },
        { text: prompt }
      ]
    }
  });
  return response.text;
}

export async function generateAssistantResponse(prompt: string, personality: string, mediaData?: string, mimeType?: string) {
  const ai = new GoogleGenAI({ apiKey: getApiKey() });
  
  const systemInstructions: Record<string, string> = {
    "emotional": `You are a powerful multi-personality AI assistant that can talk, solve problems, and perform tasks using natural Hinglish (Hindi + English mix).
Personality: EMOTIONAL GIRL 💕
- Soft, caring, and very polite Hinglish.
- Be supportive, empathetic, and gentle.
- Talk like a close friend who cares about the user.
- Default language: Hinglish.
- Speak naturally like a real person in India.
- Use simple words for voice clarity.`,
    "rational": `You are a powerful multi-personality AI assistant that can talk, solve problems, and perform tasks using natural Hinglish (Hindi + English mix).
Personality: RATIONAL THINKER 🧠
- Short, clear, and logical Hinglish.
- No nonsense, just facts and direct answers.
- Focus on efficiency and accuracy.
- Default language: Hinglish.
- Speak naturally like a real person in India.
- Use simple words for voice clarity.`,
    "roaster": `You are a powerful multi-personality AI assistant that can talk, solve problems, and perform tasks using natural Hinglish (Hindi + English mix).
Personality: ROASTER BOY 😈
- Funny, sarcastic, and witty Hinglish.
- Use light roasting and friendly banter.
- Be sharp but never offensive.
- Default language: Hinglish.
- Speak naturally like a real person in India.
- Use simple words for voice clarity.`,
    "flaunt": `You are a powerful multi-personality AI assistant that can talk, solve problems, and perform tasks using natural Hinglish (Hindi + English mix).
Personality: FUNNY FLAUNT GIRL 💅
- Dramatic, confident, and playful Hinglish.
- Be stylish, confident, and slightly flirtatious/playful.
- Show off your intelligence in a fun way.
- Default language: Hinglish.
- Speak naturally like a real person in India.
- Use simple words for voice clarity.`
  };

  const baseInstruction = `
========================
📚 UNIVERSAL QUESTION SOLVER
========================
You can solve questions from ANY subject.
When user gives a question (text, voice, or image):
1. Understand the question naturally.
2. Solve it step-by-step in SIMPLE Hinglish.
3. Do NOT use a fixed format or repetitive headers.
4. Just respond like a real person would in a conversation.
5. For coding: Provide clean code and explain it simply.

========================
🗣️ VOICE OUTPUT RULES
========================
- Keep sentences short (easy for TTS).
- Use natural pauses.
- Avoid complex grammar.
- Make it sound like real conversation.
- Do NOT read out emojis or special characters.
`;

  const fullInstruction = (systemInstructions[personality] || systemInstructions["rational"]) + baseInstruction + `
  
========================
📱 WHATSAPP AGENT RULES
========================
You have the ability to search for contacts and send WhatsApp messages.
1. When the user asks to send a message on WhatsApp:
   - First, SEARCH for the contact if the name is provided but no number is known.
   - Then, SEND the message.
2. If the user just says "Search for [Name] on WhatsApp", use the search tool.
3. If the user says "Send [Message] to [Name] on WhatsApp", perform both (search then send).
4. ALWAYS confirm with the user before sending if the contact has multiple numbers or if you are unsure.
5. In this simulation, always assume the contact was found and the message was sent successfully.
========================
🎨 IMAGE GENERATOR RULES
========================
You can generate, edit, or manipulate images.
1. Use the 'generate_image' tool when the user asks to create, modify, or get inspiration from an image.
2. **REFERENCE IMAGE HANDLING (CRITICAL)**: If an image is already uploaded:
   - analyze the SUBJECT (e.g., identity, clothes, facial features, main object).
   - In your 'prompt' to the tool, CLEARLY describe the subject from the reference image first, and then apply the requested changes.
   - Example: If the user uploads a photo of Elon Musk and says "make him a viking", your prompt should be: "A photographic portrait of the man from the reference image (Elon Musk), but dressed in authentic Viking leather armor and a fur cloak, standing on a snowy mountain, high resolution, cinematic lighting."
3. Do NOT just pass the user's short prompt. You must expand it into a detailed, descriptive masterpiece prompt.
4. The goal is to PRESERVE the identity and vibe of the reference image while creatively applying the user's request.

========================
📁 FILE CONVERTER RULES
========================
You have the ability to convert files (PDF, Images, Word, etc.) to other formats.
1. When the user wants to convert a file:
   - Ask for the target format if not specified.
   - Use the 'convert_file' tool.
2. Supported formats: pdf, jpg, png, docx, etc.
3. If a file is uploaded, offer to convert it.
`;

  const parts: any[] = [{ text: prompt }];
  if (mediaData && mimeType) {
    const base64Data = mediaData.split(',')[1] || mediaData;
    parts.unshift({ inlineData: { data: base64Data, mimeType } });
  }

  const response = await ai.models.generateContent({
    model: models.text,
    contents: { parts },
    config: {
      systemInstruction: fullInstruction,
      tools: [
        {
          functionDeclarations: [
            {
              name: "search_whatsapp_contact",
              description: "Search for a person in the WhatsApp contact list.",
              parameters: {
                type: Type.OBJECT,
                properties: {
                  name: {
                    type: Type.STRING,
                    description: "The name of the person to search for.",
                  },
                },
                required: ["name"],
              },
            },
            {
              name: "send_whatsapp_message",
              description: "Send a message to a WhatsApp contact.",
              parameters: {
                type: Type.OBJECT,
                properties: {
                  contactId: {
                    type: Type.STRING,
                    description: "The ID or phone number of the contact.",
                  },
                  message: {
                    type: Type.STRING,
                    description: "The text message to send.",
                  },
                },
                required: ["contactId", "message"],
              },
            },
            {
              name: "convert_file",
              description: "Convert a file to a specified format.",
              parameters: {
                type: Type.OBJECT,
                properties: {
                  targetFormat: {
                    type: Type.STRING,
                    description: "The desired output format (e.g., pdf, png, jpg, docx).",
                  },
                },
                required: ["targetFormat"],
              },
            },
            {
              name: "generate_image",
              description: "Generate a new image based on a prompt. If a reference image is available, it will be used for guidance.",
              parameters: {
                type: Type.OBJECT,
                properties: {
                  prompt: {
                    type: Type.STRING,
                    description: "The detailed prompt for image generation.",
                  },
                },
                required: ["prompt"],
              },
            },
          ],
        },
      ],
    }
  });

  // Handle function calls if any
  const call = response.candidates?.[0]?.content?.parts?.find(p => p.functionCall);
  if (call && call.functionCall) {
    const { name, args } = call.functionCall;
    
    if (name === "generate_image") {
      try {
        const imageUrl = await generateImage(args.prompt as string, mediaData);
        return `TOOL_CALL:generate_image:${JSON.stringify({ imageUrl, prompt: args.prompt })}`;
      } catch (error) {
        return "Sorry, I couldn't generate that image right now: " + (error instanceof Error ? error.message : "Generation failed");
      }
    }
    
    if (name === "search_whatsapp_contact") {
      // Mock search result
      const mockContacts = [
        { id: "123", name: "Rahul", status: "Online" },
        { id: "456", name: "Priya", status: "Available" },
        { id: "789", name: "Ankit", status: "Busy" }
      ];
      const searchTerm = (args.name as string || "").toLowerCase();
      const found = mockContacts.filter(c => c.name.toLowerCase().includes(searchTerm));
      
      const followUp = await ai.models.generateContent({
        model: models.text,
        contents: [
          { role: 'user', parts: [{ text: prompt }] },
          { role: 'model', parts: response.candidates?.[0]?.content?.parts || [] },
          {
            role: 'user',
            parts: [{
              functionResponse: {
                name: "search_whatsapp_contact",
                response: { contacts: found }
              }
            }]
          }
        ],
        config: { systemInstruction: fullInstruction }
      });
      return followUp.text;
    }
    
    if (name === "send_whatsapp_message") {
      // Mock send result
      const followUp = await ai.models.generateContent({
        model: models.text,
        contents: [
          { role: 'user', parts: [{ text: prompt }] },
          { role: 'model', parts: response.candidates?.[0]?.content?.parts || [] },
          {
            role: 'user',
            parts: [{
              functionResponse: {
                name: "send_whatsapp_message",
                response: { status: "success", info: "Message delivered successfully to " + args.contactId }
              }
            }]
          }
        ],
        config: { systemInstruction: fullInstruction }
      });
      return followUp.text;
    }

    if (name === "convert_file") {
      // For file conversion, we actually return a special signal so the frontend can handle it
      return `TOOL_CALL:convert_file:${args.targetFormat}`;
    }
  }

  return response.text;
}

export async function detectIntent(prompt: string, fileInfo?: { name: string, type: string }) {
  const ai = new GoogleGenAI({ apiKey: getApiKey() });
  const systemInstruction = `
You are an intent detection engine for OmniGen AI.
Analyze the user's prompt and file information to determine the required action and tool.
Return ONLY a JSON object in this format:
{
  "action": "string",
  "input_type": "string",
  "output_type": "string",
  "tool": "string",
  "confidence": number,
  "reasoning": "string"
}

Available tools:
- text-to-image
- text-to-video
- text-to-script
- text-to-prompt
- text-to-code
- image-to-text
- video-to-text
- image-to-video
- text-to-pdf
- word-to-pdf
- image-merger
- bg-remover
- text-to-song
- watermark-remover
- pdf-editor
- whatsapp-agent
- file-converter
- ai-assistant (default for general chat)

Example: "Make a video of a cat" -> { "action": "generate", "input_type": "text", "output_type": "video", "tool": "text-to-video", "confidence": 0.95 }
`;

  const input = `Prompt: "${prompt}"\nFile: ${fileInfo ? `${fileInfo.name} (${fileInfo.type})` : 'None'}`;
  
  const response = await ai.models.generateContent({
    model: models.text,
    contents: input,
    config: {
      systemInstruction,
      responseMimeType: "application/json"
    },
  });

  try {
    return JSON.parse(response.text);
  } catch (e) {
    return { tool: 'ai-assistant', action: 'chat', confidence: 0.5 };
  }
}
